import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./Nav.js"
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div id="grid-container">
          <Nav />
          <div id="main-content">
            {children}
          </div>
          <div id="foot">
            <p><Link href="inspo">Inspiration</Link></p>
            <p>© Cara 2025</p>
          </div>
        </div>
      </body>
    </html>
  );
}
